# Common configuration for all profiles
spring:
  profiles:
    active: dev
  flyway:
    enabled: true
    locations: classpath:db/migration
  thymeleaf:
    cache: false

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:bookmarksdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console

# Enable Swagger UI for dev profile
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:mem:bookmarksdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: false

# Disable Swagger UI for prod profile
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false